package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTArrayDimsAndInits.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTArrayDimsAndInits extends SimpleNode
{
    int arrayDim = 0;

    public ASTArrayDimsAndInits(int id)
    {
        super(id);
    }

    public ASTArrayDimsAndInits(NslParser p, int id)
    {
        super(p, id);
    }

    public void incrDim()
    {
        arrayDim++;
    }

    public String getArrayDimsAndInits()
    {
        Token t = first;
        Token end = last;

        StringBuilder dim = new StringBuilder(t.image);
        while (t != end)
        {
            t = t.next;
            dim.append(t.image);
        }

        return dim.toString();
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getDims()
    {
        StringBuilder dims = new StringBuilder("");
        for (int i = 0; i < arrayDim; i++)
        {
            dims.append("[]");
        }
        return dims.toString();
    }
}
