package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTArguments.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTArguments extends SimpleNode
{
    public ASTArguments(int id)
    {
        super(id);
    }

    public ASTArguments(NslParser p, int id)
    {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String[] getArguments()
    {
        if (jjtGetNumChildren() > 0)
        {
            ASTArgumentList argList = (ASTArgumentList) jjtGetChild(0);
            return argList.getArguments();
        }
        return new String[0];
    }

    public String[] getArgumentsTypes()
    {
        if (jjtGetNumChildren() > 0)
        {
            ASTArgumentList argList = (ASTArgumentList) jjtGetChild(0);
            return argList.getArgumentsTypes();
        }
        return new String[0];
    }
}
