package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTBlockStatement.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTBlockStatement extends SimpleNode
{
    public ASTBlockStatement(int id)
    {
        super(id);
    }

    public ASTBlockStatement(NslParser p, int id)
    {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
