package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTLiteral.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTLiteral extends SimpleNode
{
    public ASTLiteral(int id)
    {
        super(id);
    }

    public ASTLiteral(NslParser p, int id)
    {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getType()
    {
        String type = getNodeType();
        if (type.equals("double"))
        {
            if (first.image.indexOf("f") >= 0 || first.image.indexOf("F") >= 0)
            {
                type = "float";
            }
        }
        return type;
    }

    public String getValue()
    {

        if (jjtGetNumChildren() > 0)
        {
            SimpleNode node = (SimpleNode) jjtGetChild(0);
            if (node instanceof ASTBooleanLiteral)
            {
                return "";
            }
            else
            {
                return "null";
            }
        }
        else
        {
            return first.image;
        }
    }

    public String toXMLOpen(String prefix)
    {
        String value = getValue();
        return prefix + '<' + toString() + '>' + value;
    }
}
