package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTMethodDeclarator.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTMethodDeclarator extends SimpleNode
{
    public ASTMethodDeclarator(int id)
    {
        super(id);
    }

    public ASTMethodDeclarator(NslParser p, int id)
    {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getMethodName()
    {
        return first.image;
    }

    public String[] getFormalTypes()
    {
        ASTFormalParameters formals = (ASTFormalParameters) jjtGetChild(0);
        return formals.getTypes();
    }

    public String[] getFormalNames()
    {
        ASTFormalParameters formals = (ASTFormalParameters) jjtGetChild(0);
        return formals.getNames();
    }

    public void updateScope(NslScope scope)
    {
        String types[] = getFormalTypes();
        String names[] = getFormalNames();
        NslVariable temp;
        for (int i = 0; i < names.length; i++)
        {
            temp = new NslVariable(types[i], names[i]);
            if (!scope.addLocalVar(temp))
            {
                ASTFormalParameters variable = (ASTFormalParameters) jjtGetChild(i + 1);
                NslCompiler.printError("nslc.src.ASTMethodDeclaration", "Variable " + names[i] + " was already defined in this scope", variable.getFirstToken().beginLine, variable.getFirstToken().beginColumn);
            }
        }
    }

    public String toXMLOpen(String prefix)
    {
        String name = getMethodName();
        return prefix + '<' + toString() + " name=\"" + name + "\">";
    }
}
