package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTNslArrayDeclarator.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTNslArrayDeclarator extends SimpleNode
{
    public ASTNslArrayDeclarator(int id)
    {
        super(id);
    }

    public ASTNslArrayDeclarator(NslParser p, int id)
    {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getName()
    {
        return first.image;
    }

    public String getArrayArguments()
    {
        int num = jjtGetNumChildren();

        ASTExpression arg;
        StringBuilder args = new StringBuilder("");
        for (int i = 0; i < num; i++)
        {
            arg = (ASTExpression) jjtGetChild(i);
            args.append('[');
            args.append(arg.getExpression());
            args.append(']');
        }
        return args.toString();
    }

    public int getDim()
    {
        return jjtGetNumChildren();
    }

    public String toXMLOpen(String prefix)
    {
        String name = getName();
        return prefix + '<' + toString() + " name=\"" + name + "\">";
    }
}
