package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTPrimitiveType.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTPrimitiveType extends SimpleNode
{
    public ASTPrimitiveType(int id)
    {
        super(id);
    }

    public ASTPrimitiveType(NslParser p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getType()
    {
        Token t = first;
        Token end = last;

        StringBuilder name = new StringBuilder(t.image);
        while (t != end)
        {
            t = t.next;
            name.append(t.image);
        }
        return name.toString();
    }

    public String toXMLOpen(String prefix)
    {
        String type = getType();
        return prefix + '<' + toString() + '>' + type;
    }

}
