package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTResultType.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTResultType extends SimpleNode
{
    public ASTResultType(int id)
    {
        super(id);
    }

    public ASTResultType(NslParser p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getType()
    {
        if (jjtGetNumChildren() > 0)
        {
            ASTType typeNode = (ASTType) jjtGetChild(0);
            return typeNode.getType();
        }
        return "void";
    }

    public String toXMLOpen(String prefix)
    {
        String type = "";
        if (jjtGetNumChildren() == 0)
        {
            type = "void";
        }
        return prefix + '<' + toString() + '>' + type;
    }
}
