package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTType.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTType extends SimpleNode
{

    public ASTType(int id)
    {
        super(id);
    }

    public ASTType(NslParser p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getTypeSuffix()
    {
        SimpleNode typeNode = (SimpleNode) jjtGetChild(0);
        Token t = typeNode.getLastToken();
        Token end = last;

        StringBuilder type = new StringBuilder("");
        while (t != end)
        {
            t = t.next;
            type.append(t.image);
        }
        return type.toString();
    }

    public String getType()
    {
        SimpleNode typeNode = (SimpleNode) jjtGetChild(0);
        String type;
        if (typeNode instanceof ASTPrimitiveType)
        {
            type = ((ASTPrimitiveType) typeNode).getType();
        }
        else
        {
            type = ((ASTName) typeNode).getName();
        }
        return type + getTypeSuffix();
    }
}
