package nslc.src;/* Generated By:JJTree: Do not edit this line. nslc.src.ASTVariableDeclaratorId.java */

/* SCCS  %W--- %G% -- %U% */

// Copyright: Copyright (c) 1997-2002 University of Southern California Brain Project.
// Copyright: This software may be freely copied provided the toplevel
// Copyright: COPYRIGHT file is included with each such copy.
// Copyright: Email nsl@java.usc.edu.

// Author: Salvador Marmol

public class ASTVariableDeclaratorId extends SimpleNode
{
    public ASTVariableDeclaratorId(int id)
    {
        super(id);
    }

    public ASTVariableDeclaratorId(NslParser p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(NslParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String getName()
    {
        return first.image;
    }

    public String getTypeSuffix()
    {

        Token t = first;
        Token end = last;

        StringBuilder type = new StringBuilder("");
        while (t != end)
        {
            t = t.next;
            type.append(t.image);
        }
        return type.toString();
    }

    public String toXMLOpen(String prefix)
    {
        String name = getName();
        String type = getTypeSuffix();
        return prefix + '<' + toString() + '>' + name + type;
    }

}
