/* Generated By:JJTree&JavaCC: Do not edit this line. NslParserConstants.java */
package nslc.src;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NslParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int ABSTRACT = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int BYTE = 16;
  /** RegularExpression Id. */
  int CASE = 17;
  /** RegularExpression Id. */
  int CATCH = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int CLASS = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int CONTINUE = 22;
  /** RegularExpression Id. */
  int _DEFAULT = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int EXTENDS = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int FINAL = 29;
  /** RegularExpression Id. */
  int FINALLY = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int GOTO = 33;
  /** RegularExpression Id. */
  int IF = 34;
  /** RegularExpression Id. */
  int IMPLEMENTS = 35;
  /** RegularExpression Id. */
  int IMPORT = 36;
  /** RegularExpression Id. */
  int INSTANCEOF = 37;
  /** RegularExpression Id. */
  int INT = 38;
  /** RegularExpression Id. */
  int INTERFACE = 39;
  /** RegularExpression Id. */
  int LONG = 40;
  /** RegularExpression Id. */
  int NATIVE = 41;
  /** RegularExpression Id. */
  int NEW = 42;
  /** RegularExpression Id. */
  int NULL = 43;
  /** RegularExpression Id. */
  int PACKAGE = 44;
  /** RegularExpression Id. */
  int PRIVATE = 45;
  /** RegularExpression Id. */
  int PROTECTED = 46;
  /** RegularExpression Id. */
  int PUBLIC = 47;
  /** RegularExpression Id. */
  int RETURN = 48;
  /** RegularExpression Id. */
  int SHORT = 49;
  /** RegularExpression Id. */
  int STATIC = 50;
  /** RegularExpression Id. */
  int SUPER = 51;
  /** RegularExpression Id. */
  int SWITCH = 52;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 53;
  /** RegularExpression Id. */
  int THIS = 54;
  /** RegularExpression Id. */
  int THROW = 55;
  /** RegularExpression Id. */
  int THROWS = 56;
  /** RegularExpression Id. */
  int TRANSIENT = 57;
  /** RegularExpression Id. */
  int TRUE = 58;
  /** RegularExpression Id. */
  int TRY = 59;
  /** RegularExpression Id. */
  int VOID = 60;
  /** RegularExpression Id. */
  int VOLATILE = 61;
  /** RegularExpression Id. */
  int WHILE = 62;
  /** RegularExpression Id. */
  int STRICTFP = 63;
  /** RegularExpression Id. */
  int ASSERT = 64;
  /** RegularExpression Id. */
  int NSLIMPORT = 65;
  /** RegularExpression Id. */
  int NSLCLASS = 66;
  /** RegularExpression Id. */
  int NSLPORT = 67;
  /** RegularExpression Id. */
  int NSLINPORT = 68;
  /** RegularExpression Id. */
  int NSLOUTPORT = 69;
  /** RegularExpression Id. */
  int NSLCONSTANT = 70;
  /** RegularExpression Id. */
  int NSLCONST = 71;
  /** RegularExpression Id. */
  int NSLMODEL = 72;
  /** RegularExpression Id. */
  int NSLMODULE = 73;
  /** RegularExpression Id. */
  int NSLJAVAMODULE = 74;
  /** RegularExpression Id. */
  int NSLMATLABMODULE = 75;
  /** RegularExpression Id. */
  int CHARSTRING = 76;
  /** RegularExpression Id. */
  int VERBATIMNSLJ = 77;
  /** RegularExpression Id. */
  int VERBATIMNSLC = 78;
  /** RegularExpression Id. */
  int VERBATIMOFF = 79;
  /** RegularExpression Id. */
  int VERBATIMTEMPJ = 80;
  /** RegularExpression Id. */
  int VERBATIMTEMPC = 81;
  /** RegularExpression Id. */
  int MULTI_LINE_VERBATIM = 82;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 84;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 85;
  /** RegularExpression Id. */
  int HEX_LITERAL = 86;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 87;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 88;
  /** RegularExpression Id. */
  int EXPONENT = 89;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 90;
  /** RegularExpression Id. */
  int STRING_LITERAL = 91;
  /** RegularExpression Id. */
  int IDENTIFIER = 92;
  /** RegularExpression Id. */
  int LETTER = 93;
  /** RegularExpression Id. */
  int DIGIT = 94;
  /** RegularExpression Id. */
  int LPAREN = 95;
  /** RegularExpression Id. */
  int RPAREN = 96;
  /** RegularExpression Id. */
  int LBRACE = 97;
  /** RegularExpression Id. */
  int RBRACE = 98;
  /** RegularExpression Id. */
  int LBRACKET = 99;
  /** RegularExpression Id. */
  int RBRACKET = 100;
  /** RegularExpression Id. */
  int SEMICOLON = 101;
  /** RegularExpression Id. */
  int COMMA = 102;
  /** RegularExpression Id. */
  int DOT = 103;
  /** RegularExpression Id. */
  int ASSIGN = 104;
  /** RegularExpression Id. */
  int GT = 105;
  /** RegularExpression Id. */
  int LT = 106;
  /** RegularExpression Id. */
  int BANG = 107;
  /** RegularExpression Id. */
  int TILDE = 108;
  /** RegularExpression Id. */
  int HOOK = 109;
  /** RegularExpression Id. */
  int COLON = 110;
  /** RegularExpression Id. */
  int EQ = 111;
  /** RegularExpression Id. */
  int LE = 112;
  /** RegularExpression Id. */
  int GE = 113;
  /** RegularExpression Id. */
  int NE = 114;
  /** RegularExpression Id. */
  int SC_OR = 115;
  /** RegularExpression Id. */
  int SC_AND = 116;
  /** RegularExpression Id. */
  int INCR = 117;
  /** RegularExpression Id. */
  int DECR = 118;
  /** RegularExpression Id. */
  int PLUS = 119;
  /** RegularExpression Id. */
  int MINUS = 120;
  /** RegularExpression Id. */
  int STAR = 121;
  /** RegularExpression Id. */
  int SLASH = 122;
  /** RegularExpression Id. */
  int BIT_AND = 123;
  /** RegularExpression Id. */
  int BIT_OR = 124;
  /** RegularExpression Id. */
  int XOR = 125;
  /** RegularExpression Id. */
  int REM = 126;
  /** RegularExpression Id. */
  int LSHIFT = 127;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 128;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 129;
  /** RegularExpression Id. */
  int PLUSASSIGN = 130;
  /** RegularExpression Id. */
  int MINUSASSIGN = 131;
  /** RegularExpression Id. */
  int STARASSIGN = 132;
  /** RegularExpression Id. */
  int SLASHASSIGN = 133;
  /** RegularExpression Id. */
  int ANDASSIGN = 134;
  /** RegularExpression Id. */
  int ORASSIGN = 135;
  /** RegularExpression Id. */
  int XORASSIGN = 136;
  /** RegularExpression Id. */
  int REMASSIGN = 137;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 138;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 139;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 140;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_VERBATIM = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"strictfp\"",
    "\"assert\"",
    "\"nslImport\"",
    "\"nslClass\"",
    "\"nslPort\"",
    "\"nslInPort\"",
    "\"nslOutPort\"",
    "\"nslConstant\"",
    "\"nslConst\"",
    "\"nslModel\"",
    "\"nslModule\"",
    "\"nslJavaModule\"",
    "\"nslMatlabModule\"",
    "\"charString\"",
    "<VERBATIMNSLJ>",
    "<VERBATIMNSLC>",
    "<VERBATIMOFF>",
    "<VERBATIMTEMPJ>",
    "<VERBATIMTEMPC>",
    "<MULTI_LINE_VERBATIM>",
    "<token of kind 83>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"@\"",
  };

}
